import React, { useState } from 'react';
import { Table } from 'antd'; // Ant table

// Table colums
const columns = [
    {
      title: 'EMP ID',
      dataIndex: 'empid',    
      sorter: (a, b) => a.empid - b.empid,
      width: 60,
    },
    {
      title: 'Empolyee Name',
      dataIndex: 'name',
      filters: [
        {
          text: 'Joe',
          value: 'Joe',
        },
        {
          text: 'Category 1',
          value: 'Category 1',
        },
        {
          text: 'Category 2',
          value: 'Category 2',
        },
      ],
      filterMode: 'tree',
      filterSearch: true,
      onFilter: (value, record) => record.name.startsWith(value),
      width: 100,
    },
    {
      title: 'Department',
      dataIndex: 'department',
      filters: [
        {
          text: 'COE',
          value: 'Coe',
        },
        {
          text: 'Category 1',
          value: 'Category 1',
        },
        {
          text: 'Category 2',
          value: 'Category 2',
        },
      ],
      filterMode: 'tree',
      filterSearch: true,
      onFilter: (value, record) => record.name.startsWith(value),
      width: 100,
    },
    {
      title: 'Assigned',
      dataIndex: 'assigned',
      sorter: (a, b) => a.assigned - b.assigned,
      width: 100,
    },
    {
      title: 'In Progress',
      dataIndex: 'inprogress',
      sorter: (a, b) => a.inprogress - b.inprogress,
      width: 100,
    },
    {
      title: 'Completed',
      dataIndex: 'completed',
      sorter: (a, b) => a.completed - b.completed,
      width: 100,
    },
    {
      title: 'Escalated',
      dataIndex: 'escalated',
      sorter: (a, b) => a.escalated - b.escalated,
      width: 100,
    },
    {
      title: 'Within SLA',
      dataIndex: 'sla',
      sorter: (a, b) => a.sla - b.sla,
      width: 100,
    },
    {
      title: 'Assigned to Completed',
      dataIndex: 'assignedCompleted',
      sorter: (a, b) => a.assignedCompleted - b.assignedCompleted,
      width: 100,
    },
    {
      title: 'Assigned to Escalated',
      dataIndex: 'assignedEscalated',
      sorter: (a, b) => a.assignedEscalated - b.assignedEscalated,
      width: 100,
    },
    {
      title: 'Action',
      dataIndex: 'action',
      width: 120,
      align: 'center',
      fixed: "right",
      render: () => <div className='flex space-x-2'>
          <button className='rounded-md px-2 py-2 w-1/2 bg-white hover:bg-royal-voilet-10 border border-blue-50 text-zinc-700 hover:text-white shadow-sm font-semibold'>Mail</button>
          <button className='rounded-md px-2 py-2 w-1/2 bg-white hover:bg-royal-voilet-10 border border-blue-50 text-zinc-700 hover:text-white shadow-sm font-semibold'>Action</button>
        </div>,
    },
  ];
// Table row data
  const tableData = {
    daily: [
      {
        key: '1',
        empid: '1',
        name: 'John Brown',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '2',
        empid: '2',
        name: 'Jim Green',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '3',
        empid: '3',
        name: 'Joe Black',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '4',
        empid: '4',
        name: 'Jim Red',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '5',
        empid: '5',
        name: 'John Brown',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '6',
        empid: '6',
        name: 'Jim Green',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '7',
        empid: '7',
        name: 'Joe Black',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '8',
        empid: '8',
        name: 'Jim Red',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '9',
        empid: '9',
        name: 'John Brown',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '10',
        empid: '10',
        name: 'Jim Green',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '11',
        empid: '11',
        name: 'Black',
        department: 'COE',
        assigned: 22,
        inprogress: 98,
        completed: 75,
        escalated: 31,
        sla: 98,
        assignedCompleted: '43%',
        assignedEscalated: '12%',
      },
      {
        key: '12',
        empid: '12',
        name: 'Red',
        department: 'COE',
        assigned: 54,
        inprogress: 76,
        completed: 14,
        escalated: 93,
        sla: 80,
        assignedCompleted: '95%',
        assignedEscalated: '75%',
      },
      {
        key: '13',
        empid: '13',
        name: 'Brown',
        department: 'COE',
        assigned: 10,
        inprogress: 65,
        completed: 59,
        escalated: 34,
        sla: 20,
        assignedCompleted: '15%',
        assignedEscalated: '54%',
      },
      {
        key: '14',
        empid: '14',
        name: 'Green',
        department: 'COE',
        assigned: 94,
        inprogress: 30,
        completed: 19,
        escalated: 63,
        sla: 70,
        assignedCompleted: '69%',
        assignedEscalated: '43%',
      },
      {
        key: '15',
        empid: '15',
        name: 'Black',
        department: 'COE',
        assigned: 22,
        inprogress: 98,
        completed: 75,
        escalated: 31,
        sla: 98,
        assignedCompleted: '43%',
        assignedEscalated: '12%',
      },
      {
        key: '16',
        empid: '16',
        name: 'Red',
        department: 'COE',
        assigned: 54,
        inprogress: 76,
        completed: 14,
        escalated: 93,
        sla: 80,
        assignedCompleted: '95%',
        assignedEscalated: '75%',
      },
      {
        key: '17',
        empid: '17',
        name: 'Brown',
        department: 'COE',
        assigned: 10,
        inprogress: 65,
        completed: 59,
        escalated: 34,
        sla: 20,
        assignedCompleted: '15%',
        assignedEscalated: '54%',
      },
      {
        key: '18',
        empid: '18',
        name: 'Green',
        department: 'COE',
        assigned: 94,
        inprogress: 30,
        completed: 19,
        escalated: 63,
        sla: 70,
        assignedCompleted: '69%',
        assignedEscalated: '43%',
      },
      {
        key: '19',
        empid: '19',
        name: 'Joe Black',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '20',
        empid: '20',
        name: 'Jim Red',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '21',
        empid: '21',
        name: 'John Brown',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '22',
        empid: '22',
        name: 'Jim Green',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '23',
        empid: '23',
        name: 'Joe Black',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '24',
        empid: '24',
        name: 'Jim Red',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
    ],
    weekly: [
      {
        key: '1',
        empid: '1',
        name: 'Brown',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '2',
        empid: '2',
        name: 'Green',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '3',
        empid: '3',
        name: 'Black',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '4',
        empid: '4',
        name: 'Red',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '5',
        empid: '5',
        name: 'Brown',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '6',
        empid: '6',
        name: 'Green',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '7',
        empid: '7',
        name: 'Black',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '8',
        empid: '8',
        name: 'Red',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '9',
        empid: '9',
        name: 'Brown',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '10',
        empid: '10',
        name: 'Green',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '11',
        empid: '11',
        name: 'Black',
        department: 'COE',
        assigned: 22,
        inprogress: 98,
        completed: 75,
        escalated: 31,
        sla: 98,
        assignedCompleted: '43%',
        assignedEscalated: '12%',
      },
      {
        key: '12',
        empid: '12',
        name: 'Red',
        department: 'COE',
        assigned: 54,
        inprogress: 76,
        completed: 14,
        escalated: 93,
        sla: 80,
        assignedCompleted: '95%',
        assignedEscalated: '75%',
      },
      {
        key: '13',
        empid: '13',
        name: 'Brown',
        department: 'COE',
        assigned: 10,
        inprogress: 65,
        completed: 59,
        escalated: 34,
        sla: 20,
        assignedCompleted: '15%',
        assignedEscalated: '54%',
      },
      {
        key: '14',
        empid: '14',
        name: 'Green',
        department: 'COE',
        assigned: 94,
        inprogress: 30,
        completed: 19,
        escalated: 63,
        sla: 70,
        assignedCompleted: '69%',
        assignedEscalated: '43%',
      },
      {
        key: '15',
        empid: '15',
        name: 'Black',
        department: 'COE',
        assigned: 22,
        inprogress: 98,
        completed: 75,
        escalated: 31,
        sla: 98,
        assignedCompleted: '43%',
        assignedEscalated: '12%',
      },
      {
        key: '16',
        empid: '16',
        name: 'Red',
        department: 'COE',
        assigned: 54,
        inprogress: 76,
        completed: 14,
        escalated: 93,
        sla: 80,
        assignedCompleted: '95%',
        assignedEscalated: '75%',
      },
      {
        key: '17',
        empid: '17',
        name: 'Brown',
        department: 'COE',
        assigned: 10,
        inprogress: 65,
        completed: 59,
        escalated: 34,
        sla: 20,
        assignedCompleted: '15%',
        assignedEscalated: '54%',
      },
      {
        key: '18',
        empid: '18',
        name: 'Green',
        department: 'COE',
        assigned: 94,
        inprogress: 30,
        completed: 19,
        escalated: 63,
        sla: 70,
        assignedCompleted: '69%',
        assignedEscalated: '43%',
      },
      {
        key: '19',
        empid: '19',
        name: 'Joe Black',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '20',
        empid: '20',
        name: 'Jim Red',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '21',
        empid: '21',
        name: 'John Brown',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '22',
        empid: '22',
        name: 'Jim Green',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '23',
        empid: '23',
        name: 'Joe Black',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '24',
        empid: '24',
        name: 'Jim Red',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
    ],
    monthly: [
      {
        key: '1',
        empid: '1',
        name: 'John',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '2',
        empid: '2',
        name: 'Jim',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '3',
        empid: '3',
        name: 'Joe',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '4',
        empid: '4',
        name: 'Jim',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '5',
        empid: '5',
        name: 'John',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '6',
        empid: '6',
        name: 'Jim',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '7',
        empid: '7',
        name: 'Joe',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '8',
        empid: '8',
        name: 'Jim',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '9',
        empid: '9',
        name: 'John',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '10',
        empid: '10',
        name: 'Jim',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '11',
        empid: '11',
        name: 'Black',
        department: 'COE',
        assigned: 22,
        inprogress: 98,
        completed: 75,
        escalated: 31,
        sla: 98,
        assignedCompleted: '43%',
        assignedEscalated: '12%',
      },
      {
        key: '12',
        empid: '12',
        name: 'Red',
        department: 'COE',
        assigned: 54,
        inprogress: 76,
        completed: 14,
        escalated: 93,
        sla: 80,
        assignedCompleted: '95%',
        assignedEscalated: '75%',
      },
      {
        key: '13',
        empid: '13',
        name: 'Brown',
        department: 'COE',
        assigned: 10,
        inprogress: 65,
        completed: 59,
        escalated: 34,
        sla: 20,
        assignedCompleted: '15%',
        assignedEscalated: '54%',
      },
      {
        key: '14',
        empid: '14',
        name: 'Green',
        department: 'COE',
        assigned: 94,
        inprogress: 30,
        completed: 19,
        escalated: 63,
        sla: 70,
        assignedCompleted: '69%',
        assignedEscalated: '43%',
      },
      {
        key: '15',
        empid: '15',
        name: 'Black',
        department: 'COE',
        assigned: 22,
        inprogress: 98,
        completed: 75,
        escalated: 31,
        sla: 98,
        assignedCompleted: '43%',
        assignedEscalated: '12%',
      },
      {
        key: '16',
        empid: '16',
        name: 'Red',
        department: 'COE',
        assigned: 54,
        inprogress: 76,
        completed: 14,
        escalated: 93,
        sla: 80,
        assignedCompleted: '95%',
        assignedEscalated: '75%',
      },
      {
        key: '17',
        empid: '17',
        name: 'Brown',
        department: 'COE',
        assigned: 10,
        inprogress: 65,
        completed: 59,
        escalated: 34,
        sla: 20,
        assignedCompleted: '15%',
        assignedEscalated: '54%',
      },
      {
        key: '18',
        empid: '18',
        name: 'Green',
        department: 'COE',
        assigned: 94,
        inprogress: 30,
        completed: 19,
        escalated: 63,
        sla: 70,
        assignedCompleted: '69%',
        assignedEscalated: '43%',
      },
      {
        key: '19',
        empid: '19',
        name: 'Joe Black',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '20',
        empid: '20',
        name: 'Jim Red',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '21',
        empid: '21',
        name: 'John Brown',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '22',
        empid: '22',
        name: 'Jim Green',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '23',
        empid: '23',
        name: 'Joe Black',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
      {
        key: '24',
        empid: '24',
        name: 'Jim Red',
        department: 'COE',
        assigned: Math.floor(Math.random() * 100),
        inprogress: Math.floor(Math.random() * 100),
        completed: Math.floor(Math.random() * 100),
        escalated: Math.floor(Math.random() * 100),
        sla: Math.floor(Math.random() * 100),
        assignedCompleted: Math.floor(Math.random() * 100) + '%',
        assignedEscalated: Math.floor(Math.random() * 100) + '%',
      },
    ],
};

// rowSelection object indicates the need for row selection
const rowSelection = {
    onChange: (selectedRowKeys, selectedRows) => {
      console.log(`selectedRowKeys: ${selectedRowKeys}`, 'selectedRows: ', selectedRows);
    },
    getCheckboxProps: (record) => ({
      disabled: record.name === 'Disabled User',
      // Column configuration not to be checked
      name: record.name,
    }),
  };

const TableList = ( { period } ) => {
  
  const [selectionType, setSelectionType] = useState('checkbox');

  const res = tableData[period];

  return(
    <Table 
      columns={columns} 
      dataSource={res} 
      rowSelection={{
        type: selectionType,
        ...rowSelection,
      }}
      scroll={{ x: 1500 }}
      sticky={true}
    />
  )
}
export default TableList;